name: Experiment Proposal
description: Propose a new experiment for the Agentic Submission Project
title: "[EXPERIMENT]: "
labels: ["experiment", "proposal", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Propose a new experiment for our ASP research!
  - type: input
    id: experiment-name
    attributes:
      label: Experiment Name
      description: A clear, descriptive name for the experiment
      placeholder: "e.g., Multi-Agent Coordination Test"
    validations:
      required: true
  - type: input
    id: jira-ticket
    attributes:
      label: Associated Jira Ticket
      description: Link to the Jira ticket for this experiment
      placeholder: "https://yourdomain.atlassian.net/browse/TICKET-123"
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Experiment Category
      description: What type of experiment is this?
      options:
        - AI Proof of Concept
        - Web Automation
        - Other (specify in description)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What does this experiment do and why is it useful?
    validations:
      required: true